In [128]:

import pandas as pd
import numpy as np
from pathlib import Path

# Current folder 
BASE_PATH = Path(".")

# Load all CSV files
customers = pd.read_csv(BASE_PATH / "customers.csv")
accounts = pd.read_csv(BASE_PATH / "accounts.csv")
agents = pd.read_csv(BASE_PATH / "agents.csv")
transaction_types = pd.read_csv(BASE_PATH / "transaction_types.csv")
transactions = pd.read_csv(BASE_PATH / "transactions.csv")

print("All files loaded successfully!")

All files loaded successfully!

In [130]:
print(customers.shape)
print(accounts.shape)
print(agents.shape)
print(transaction_types.shape)
print(transactions.shape)

(1000, 6)
(1000, 5)
(100, 5)
(5, 2)
(20000, 10)

In [10]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        1000 non-null   object
 1   name               1000 non-null   object
 2   gender             1000 non-null   object
 3   age                1000 non-null   int64
 4   city               1000 non-null   object
 5   registration_date  1000 non-null   object
dtypes: int64(1), object(5)
memory usage: 47.0+ KB

In [12]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    20000 non-null  object
 1   customer_id       20000 non-null  object
 2   agent_id          20000 non-null  object
 3   type_id           20000 non-null  object
 4   amount            20000 non-null  float64
 5   transaction_date  20000 non-null  object
 6   transaction_time  20000 non-null  object
 7   status            20000 non-null  object
 8   channel           20000 non-null  object
 9   fee               20000 non-null  float64
dtypes: float64(2), object(8)
memory usage: 1.5+ MB

In [14]:
transactions.head()

,transaction_id,customer_id,agent_id,type_id,amount,transaction_date,transaction_time,status,channel,fee
0,T000001,C0214,AG030,TT05,1640.0,2025-07-16,00:24:00,Success,Agent,8.20
1,T000002,C0934,AG018,TT01,1940.0,2025-06-07,06:44:00,Success,Agent,0.00
2,T000003,C0704,AG098,TT01,4430.0,2025-07-23,04:36:00,Success,App,22.15
3,T000004,C0507,AG026,TT01,4680.0,2025-07-15,04:59:00,Success,Agent,46.80
4,T000005,C0350,AG100,TT02,1680.0,2025-08-04,08:10:00,Failed,App,16.80

In [42]:
transactions.describe()

             amount           fee
count  20000.000000  20000.000000
mean    2609.651000     13.763235
std     2501.094095     21.634111
min       50.000000      0.000000
25%     1010.000000      0.000000
50%     1770.000000      6.300000
75%     3310.000000     17.950000
max    56090.000000    447.100000

In [18]:
transactions.isnull().sum()

transaction_id      0
customer_id         0
agent_id            0
type_id             0
amount              0
transaction_date    0
transaction_time    0
status              0
channel             0
fee                 0
dtype: int64

In [20]:
transactions.duplicated().sum()

0

In [22]:
datasets = {
    "Customers": customers,
    "Accounts": accounts,
    "Agents": agents,
    "Transaction Types": transaction_types,
    "Transactions": transactions
}

for name, df in datasets.items():
    print("\n", name)
    print("Shape:", df.shape)
    print("Duplicates:", df.duplicated().sum())
    print("Missing values:")
    print(df.isnull().sum())

 Customers
Shape: (1000, 6)
Duplicates: 0
Missing values:
customer_id          0
name                 0
gender               0
age                  0
city                 0
registration_date    0
dtype: int64

 Accounts
Shape: (1000, 5)
Duplicates: 0
Missing values:
account_id      0
customer_id     0
account_type    0
status          0
opening_date    0
dtype: int64

 Agents
Shape: (100, 5)
Duplicates: 0
Missing values:
agent_id      0
agent_name    0
city          0
region        0
join_date     0
dtype: int64

 Transaction Types
Shape: (5, 2)
Duplicates: 0
Missing values:
type_id             0
transaction_type    0
dtype: int64

 Transactions
Shape: (20000, 10)
Duplicates: 0
Missing values:
transaction_id      0
customer_id         0
agent_id            0
type_id             0
amount              0
transaction_date    0
transaction_time    0
status              0
channel             0
fee                 0
dtype: int64

In [40]:
##Customers Cleaning
customers = customers.drop_duplicates()

In [26]:
customers["customer_id"].duplicated().sum()

0

In [30]:
##Remove Duplicate
customers = customers.drop_duplicates(
    subset="customer_id",
    keep="first"
)

In [32]:
##Text Cleaning
customers["name"] = (
    customers["name"]
    .astype("string")
    .str.strip()
)

customers["gender"] = (
    customers["gender"]
    .astype("string")
    .str.strip()
    .str.title()
)

customers["city"] = (
    customers["city"]
    .astype("string")
    .str.strip()
    .str.title()
)

In [34]:
##Date
customers["registration_date"] = pd.to_datetime(
    customers["registration_date"],
    errors="coerce"
)

In [36]:
##Age Validation
customers["age"] = pd.to_numeric(
    customers["age"],
    errors="coerce"
)

customers.loc[
    ~customers["age"].between(18, 100),
    "age"
] = np.nan

In [44]:
##Agent Cleaning
agents = agents.drop_duplicates()

agents = agents.drop_duplicates(
    subset="agent_id",
    keep="first"
)

In [46]:
agents["agent_name"] = (
    agents["agent_name"]
    .astype("string")
    .str.strip()
)

agents["city"] = (
    agents["city"]
    .astype("string")
    .str.strip()
    .str.title()
)

agents["region"] = (
    agents["region"]
    .astype("string")
    .str.strip()
    .str.title()
)

In [48]:
##Date
agents["join_date"] = pd.to_datetime(
    agents["join_date"],
    errors="coerce"
)

In [50]:
##Accounts Cleaning
accounts = accounts.drop_duplicates()

accounts = accounts.drop_duplicates(
    subset="account_id",
    keep="first"
)

In [52]:
accounts["account_type"] = (
    accounts["account_type"]
    .astype("string")
    .str.strip()
    .str.title()
)

accounts["status"] = (
    accounts["status"]
    .astype("string")
    .str.strip()
    .str.title()
)

In [56]:
##Date
accounts["opening_date"] = pd.to_datetime(
    accounts["opening_date"],
    errors="coerce"
)

In [58]:
##Check invalid Customer
invalid_accounts = accounts[
    ~accounts["customer_id"].isin(
        customers["customer_id"]
    )
]

print(invalid_accounts)

Empty DataFrame
Columns: [account_id, customer_id, account_type, status, opening_date]
Index: []

In [60]:
##Then Remove
accounts = accounts[
    accounts["customer_id"].isin(
        customers["customer_id"]
    )
]

In [62]:
##Transaction Types Cleaning
transaction_types = transaction_types.drop_duplicates()

transaction_types = transaction_types.drop_duplicates(
    subset="type_id",
    keep="first"
)

In [64]:
transaction_types["transaction_type"] = (
    transaction_types["transaction_type"]
    .astype("string")
    .str.strip()
    .str.title()
)

In [66]:
##Transactions Cleaning
transactions = transactions.drop_duplicates()

In [68]:
transactions = transactions.drop_duplicates(
    subset="transaction_id",
    keep="first"
)

In [70]:
## IDs
id_columns = [
    "transaction_id",
    "customer_id",
    "agent_id",
    "type_id"
]

for col in id_columns:
    transactions[col] = (
        transactions[col]
        .astype(str)
        .str.strip()
    )

In [72]:
##Amount
transactions["amount"] = pd.to_numeric(
    transactions["amount"],
    errors="coerce"
)

In [74]:
##Invalid Amount
transactions.loc[
    transactions["amount"] <= 0,
    "amount"
] = np.nan

In [76]:
##Fee
transactions["fee"] = pd.to_numeric(
    transactions["fee"],
    errors="coerce"
)

In [78]:
##Negative Fee
transactions.loc[
    transactions["fee"] < 0,
    "fee"
] = np.nan

In [80]:
## Date & Time

In [82]:
transactions["transaction_date"] = pd.to_datetime(
    transactions["transaction_date"],
    errors="coerce"
)

In [84]:
##Time
transactions["transaction_time"] = pd.to_datetime(
    transactions["transaction_time"],
    format="%H:%M:%S",
    errors="coerce"
).dt.time

In [86]:
##Status
transactions["status"] = (
    transactions["status"]
    .astype("string")
    .str.strip()
    .str.title()
)

In [88]:
##Channel
transactions["channel"] = (
    transactions["channel"]
    .astype("string")
    .str.strip()
    .str.title()
)

In [90]:
##Foreign Key Validation

In [92]:
##Customer validation
transactions[
    ~transactions["customer_id"].isin(
        customers["customer_id"]
    )
]

Empty DataFrame
Columns: [transaction_id, customer_id, agent_id, type_id, amount, transaction_date, transaction_time, status, channel, fee]
Index: []

In [94]:
##Agent validation
transactions[
    ~transactions["agent_id"].isin(
        agents["agent_id"]
    )
]

Empty DataFrame
Columns: [transaction_id, customer_id, agent_id, type_id, amount, transaction_date, transaction_time, status, channel, fee]
Index: []

In [96]:
##Transaction type validation
transactions[
    ~transactions["type_id"].isin(
        transaction_types["type_id"]
    )
]

Empty DataFrame
Columns: [transaction_id, customer_id, agent_id, type_id, amount, transaction_date, transaction_time, status, channel, fee]
Index: []

In [98]:
##valid transaction
transactions = transactions[
    transactions["customer_id"].isin(
        customers["customer_id"]
    )
    &
    transactions["agent_id"].isin(
        agents["agent_id"]
    )
    &
    transactions["type_id"].isin(
        transaction_types["type_id"]
    )
]

In [100]:
##Derived Columns

In [102]:
##Month
transactions["transaction_month"] = (
    transactions["transaction_date"]
    .dt.to_period("M")
    .astype(str)
)

In [104]:
##Year
transactions["transaction_year"] = (
    transactions["transaction_date"].dt.year
)

In [106]:
##Month Number
transactions["transaction_month_num"] = (
    transactions["transaction_date"].dt.month
)

In [108]:
##Net Amount
transactions["net_amount"] = (
    transactions["amount"]
    - transactions["fee"].fillna(0)
)

In [110]:
##Final Data Quickly Check

In [112]:
for name, df in datasets.items():

    print("\n====================")
    print(name)

    print("Rows:", len(df))
    print("Columns:", len(df.columns))

    print(
        "Duplicate rows:",
        df.duplicated().sum()
    )

    print("Missing values:")
    print(df.isnull().sum())

====================
Customers
Rows: 1000
Columns: 6
Duplicate rows: 0
Missing values:
customer_id          0
name                 0
gender               0
age                  0
city                 0
registration_date    0
dtype: int64

====================
Accounts
Rows: 1000
Columns: 5
Duplicate rows: 0
Missing values:
account_id      0
customer_id     0
account_type    0
status          0
opening_date    0
dtype: int64

====================
Agents
Rows: 100
Columns: 5
Duplicate rows: 0
Missing values:
agent_id      0
agent_name    0
city          0
region        0
join_date     0
dtype: int64

====================
Transaction Types
Rows: 5
Columns: 2
Duplicate rows: 0
Missing values:
type_id             0
transaction_type    0
dtype: int64

====================
Transactions
Rows: 20000
Columns: 10
Duplicate rows: 0
Missing values:
transaction_id      0
customer_id         0
agent_id            0
type_id             0
amount              0
transaction_date    0
transaction_time    0
status              0
channel             0
fee                 0
dtype: int64

In [114]:
transactions.describe()

,amount,transaction_date,fee,transaction_year,transaction_month_num,net_amount
count,20000.000000,20000,20000.000000,20000.0,20000.000000,20000.000000
mean,2609.651000,2025-07-01 17:58:59.520000,13.763235,2025.0,6.512600,2595.887765
min,50.000000,2025-01-01 00:00:00,0.000000,2025.0,1.000000,49.250000
25%,1010.000000,2025-03-31 00:00:00,0.000000,2025.0,3.000000,1004.950000
50%,1770.000000,2025-07-01 00:00:00,6.300000,2025.0,7.000000,1761.150000
75%,3310.000000,2025-10-02 00:00:00,17.950000,2025.0,10.000000,3290.000000
max,56090.000000,2025-12-31 00:00:00,447.100000,2025.0,12.000000,55809.550000
std,2501.094095,NaN,21.634111,0.0,3.457129,2488.357461

In [116]:
##Save Cleaned Data

In [134]:
clean_path = BASE_PATH / "Cleaned"

clean_path.mkdir(
    parents=True,
    exist_ok=True
)

In [136]:
customers.to_csv(
    clean_path / "customers_clean.csv",
    index=False
)

accounts.to_csv(
    clean_path / "accounts_clean.csv",
    index=False
)

agents.to_csv(
    clean_path / "agents_clean.csv",
    index=False
)

transaction_types.to_csv(
    clean_path / "transaction_types_clean.csv",
    index=False
)

transactions.to_csv(
    clean_path / "transactions_clean.csv",
    index=False
)